# Generated by Django 5.2.13 on 2026-05-04 16:22

import django.db.models.deletion
import simple_history.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models

import editable_pages.conf


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditablePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=editable_pages.conf.get_page_type_choices, help_text='Logical page type used for filtering and host-specific routing.', max_length=50)),
                ('title', models.CharField(help_text='Human-friendly page title.', max_length=200)),
                ('slug', models.SlugField(help_text='Stable public slug.', max_length=200, unique=True)),
                ('table_of_contents', tinymce.models.HTMLField(blank=True, help_text='Optional HTML table of contents.')),
                ('content', tinymce.models.HTMLField(help_text='Trusted rich HTML content managed by operators.')),
                ('meta_description', models.CharField(blank=True, help_text='Optional SEO summary.', max_length=160)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers are displayed first.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the page is publicly visible.')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this page.')),
                ('content_source', models.CharField(blank=True, choices=[('', 'Manual (Admin)'), ('fixture', 'Imported from fixture')], default='', help_text='How this page was created.', max_length=20)),
                ('force_cache_refresh', models.BooleanField(default=False, help_text='Trigger host-specific cache invalidation hooks on the next save.')),
                ('version_notes', models.TextField(blank=True, help_text='Optional notes about this revision.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(blank=True, help_text='Optional parent page for hierarchical navigation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_pages', to='editable_pages.editablepage')),
            ],
            options={
                'verbose_name': 'Editable Page',
                'verbose_name_plural': 'Editable Pages',
                'ordering': ['display_order', 'page_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEditablePage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('page_type', models.CharField(choices=editable_pages.conf.get_page_type_choices, help_text='Logical page type used for filtering and host-specific routing.', max_length=50)),
                ('title', models.CharField(help_text='Human-friendly page title.', max_length=200)),
                ('slug', models.SlugField(help_text='Stable public slug.', max_length=200)),
                ('table_of_contents', tinymce.models.HTMLField(blank=True, help_text='Optional HTML table of contents.')),
                ('content', tinymce.models.HTMLField(help_text='Trusted rich HTML content managed by operators.')),
                ('meta_description', models.CharField(blank=True, help_text='Optional SEO summary.', max_length=160)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers are displayed first.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the page is publicly visible.')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this page.')),
                ('content_source', models.CharField(blank=True, choices=[('', 'Manual (Admin)'), ('fixture', 'Imported from fixture')], default='', help_text='How this page was created.', max_length=20)),
                ('force_cache_refresh', models.BooleanField(default=False, help_text='Trigger host-specific cache invalidation hooks on the next save.')),
                ('version_notes', models.TextField(blank=True, help_text='Optional notes about this revision.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last modified this page.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(blank=True, db_constraint=False, help_text='Optional parent page for hierarchical navigation.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='editable_pages.editablepage')),
            ],
            options={
                'verbose_name': 'historical Editable Page',
                'verbose_name_plural': 'historical Editable Pages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='editablepage',
            index=models.Index(fields=['page_type'], name='editable_pa_page_ty_85be12_idx'),
        ),
        migrations.AddIndex(
            model_name='editablepage',
            index=models.Index(fields=['slug'], name='editable_pa_slug_6c67f8_idx'),
        ),
        migrations.AddIndex(
            model_name='editablepage',
            index=models.Index(fields=['is_active'], name='editable_pa_is_acti_abf115_idx'),
        ),
        migrations.AddIndex(
            model_name='editablepage',
            index=models.Index(fields=['display_order'], name='editable_pa_display_be1265_idx'),
        ),
        migrations.AddIndex(
            model_name='editablepage',
            index=models.Index(fields=['parent_page'], name='editable_pa_parent__d32619_idx'),
        ),
        migrations.AddIndex(
            model_name='editablepage',
            index=models.Index(fields=['is_featured'], name='editable_pa_is_feat_020cc0_idx'),
        ),
    ]
