# Generated by Django 5.2.13 on 2026-07-11 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editable_pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='editablepage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated users only')], default='public', help_text='Who can access this page through the read-only API.', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaleditablepage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated users only')], default='public', help_text='Who can access this page through the read-only API.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='editablepage',
            index=models.Index(fields=['visibility'], name='editable_pa_visibil_10b83e_idx'),
        ),
    ]
